### ISSUE TITLE
Ionice with deadline scheduler

### ISSUE THREAD

**Issue by seckin206** [assafmo/couchdb-linux-performance#1]
Hi, 

Thanks for creating this small but valuable repo.

Readme suggests to use `deadline` scheduler and also `ionice` command. Unfortunately, `ionice` is not effective when using deadline scheduler since deadline scheduler doesn't take process priorities into account.

I can create a PR, to put a small warning in the section for `ionice` if you are still maintaining this repo.

**Comment by assafmo** [comment]
Yes, thank you! I'd love to approve you PR. 😊

**Comment by seckin206** [comment]
opened #2 for adding the warning
